### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ludurr** [cubeFS/cubefs#1349]
**Describe the bug**
Hi,
we are currently testing IO operations on Persistent Volume mounted to POD and  provisioned by CubeFS. CFS is hosted within  k8s Rancher RKE2 version `v1.22.4+rke2r1`. Chubaofs is deployed via helm charts. Any hints are welcomed. Any an idea where could be a bottleneck?
THank you

**Environment**
```
 server: chubaofs/cfs-server:2.4.0
  client: chubaofs/cfs-client:2.2.2
  csi_driver: chubaofs/cfs-csi-driver:2.2.2.110.0
  csi_provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0
  driver_registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.4.0
  csi_attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
```

**To Reproduce**
```
# chubaofs deployed on SSD using k8s helm chart
root@cfs-csi-demo-ssd-6b48585589-56vkc:/# dd if=/dev/zero of=/usr/share/nginx/html/test1.img bs=1G count=1 oflag=dsync
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 53.4011 s, 20.1 MB/s
```

```
# for comparison MooseFS (k8s node level installation) on two nodes:

[root@node mfs]# dd if=/dev/zero of=/mnt/mfs/test1.img bs=1G count=1 oflag=dsync
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 1.51547 s, 709 MB/s
```

**Expected behavior**
Expected better IO performance 

**Additional context**

**Comment by shuoranliu** [comment]
@ludurr please change "oflag=dsync" to "conv=fsync" and test again. 

Because "dsync" uses synchronized IO and chubaofs waits for the write response before issuing the next one. But I have no idea whether MooseFS waits for each write's reponse in synchronized IO mode. As for "fsync", dd uses normal writes, which is more likely what we do in real product, and invokes "fsync" system call at the end of the test to make sure data is durable.

**Comment by shuoranliu** [comment]
@ludurr I'm going to close this issue. Please feel free to re-open if there is any further question.
