### ISSUE TITLE
[Bug] when volume usage reaches its capacity, writing data to the volume is allowed

### ISSUE THREAD

**Issue by M1eyu2018** [cubefs/cubefs#1677]
When volume usage reaches its capacity，writing data to the volume is allowed until there is no writable data partition
so that volume usage exceeds capacity.

**Comment by true1064** [comment]
This problem is fixed. Related pr or commit：

-  [enhance: add a configurable switch to control whether the volume's data partitions become read-only when the volume is full]:
- - https://github.com/cubefs/cubefs/commit/594cc63b502a91d37e4208c414cbae0058b89369
- - https://github.com/cubefs/cubefs/pull/1829
