### ISSUE TITLE
[Feature]: try to reduce load of datanode and metanode

### ISSUE THREAD

**Issue by pengtianyue025** [cubefs/cubefs#1919]
**Describe the solution you'd like**
too many partitions may cost a lot cpu, io resource, that cause node's load high, and become slow, try to reduce load.

**Additional context**

**Comment by setcy** [comment]
Hello @Victor1319, I encountered some questions while processing the issue.

Does the master need to notify DataNodes and MetaNodes to stop activities on their partitions? If the answer is yes, it will lead to two ways of stopping: synchronous and asynchronous. Below, I will explain my understanding of both methods.

### Synchronous stopping

Synchronous stopping is difficult to handle in cases of partial errors. For example, if the master notifies the DataNode to stop successfully, but an error occurs when notifying the MetaNode, how should it be handled? If a rollback is chosen, what happens if an error occurs during the rollback process?

### Asynchronous stopping

Asynchronous stopping is more complex. Three additional status, "markSleep", "sleep", and "markNormal", need to be added to the volume. A scheduled task is required to handle volumes marked as "markSleep" and "markNormal", and once all tasks are completed, they are re-marked as sleep and normal. I prefer this approach, but is there a better solution?

**Comment by Victor1319** [comment]
Hello @setcy, after careful consideration about this issue, I feel that if you are not very familiar with the cubefs system, it is too difficult to realize the ability to hibernate. 
You need to consider the state of the volume, the state of the partition, the interaction with each node, and the migration process.
The **main problem** of this issue is that when there are too many partition, the node load is high, I suggest that you can consider how to reduce the load.
For example, you can increase the interval of some scheduled tasks (configurable), and the start time of scheduled tasks is more dispersed, tasks eg: `dp size comute`,  `mp snapshot`, `dp crc compute`, and so on.
If you want to implement it in this way, please tell me, and I would adjust the title of the issue for you

**Comment by setcy** [comment]
> For example, you can increase the interval of some scheduled tasks (configurable), and the start time of scheduled tasks is more dispersed, tasks eg: `dp size comute`, `mp snapshot`, `dp crc compute`, and so on.
OK, I will try to implement it in this way. Please adjust the title for me, thank you.

**Comment by setcy** [comment]
Hi @Victor1319, I have implemented the functionality to randomly increase the start time of each scheduled task by 0 to 30 seconds, in order to achieve a dispersed task start time, see #2062. However, I am unsure about the best way to expose this modification feature to the users. Should each partition have an independently adjustable scheduled task time, where the user can modify the time for each partition, or there should have same scheduled task time for all partitions within each node/zone/nodeset?

**Comment by setcy** [comment]
I have completed part of this issue and need help checking if the development direction is correct. See https://github.com/cubefs/cubefs/pull/2068
